version: "3.7"
services: 
  notebook:
    build: 
      context: .github/actions/
      dockerfile: Dockerfile
    entrypoint: jupyter notebook
    ports: 
      - 8888:8888
    volumes: 
      - ./workbooks:/home/jovyan/nnw