name: Execute Workbooks
on:
  push:
    branches:
      - master
jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute Workbooks
        uses: ./.github/actions/jupytext-execute
        with:
          notebookFiles: 'workbooks/*.Rmd'
      - name: Deploy GitHub Pages
        uses: maxheld83/ghpages@v0.2.1
        env:
          GH_PAT: ${{ secrets.ACCESS_TOKEN }}
          BUILD_DIR: workbooks/