name: Execute Workbooks
on:
  push:
    branches:
      - master
jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute Workbooks
        uses: ./.github/actions/jupytext-execute
        with:
          notebookFiles: 'workbooks/*.Rmd'
      - run: ls