name: Execute Workbooks
on:
  push:
    branches:
      - master
jobs:
  execute:
    name: Execute
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Execute Workbooks
        uses: ./.github/actions/juyptext-execute
        with:
          notebookFiles: '*.Rmd'
      - run: ls